### ISSUE TITLE
Youtube Video Implementation

### ISSUE THREAD

**Issue by abhisuri97** [trishume/eyeLike#11]
I was wondering what settings I would need to adjust to get performance and appearance similar to those seen in the Youtube Video on the blog post.

**Comment by trishume** [comment]
Read the text of the blog post, the video is not mine, it's by the author of the paper which my code is based on, it uses a different implementation. 

For one he uses a lower resolution and smaller eye regions, and he doesn't have as many debugging views. If you comment out the debugging views and reduce the eye resolution constants you can get similar performance.

Really to get good performance though without downscaling the technique needs a major change, see #3
