### ISSUE TITLE
Red channel vs Grayscale in DetectandDisplay

### ISSUE THREAD

**Issue by JohnMichaelBurke** [trishume/eyeLike#4]
I am just curious why you chose to do this? Is there a boost in performance in using the red channel as opposed to grayscale in DetectandDisplay @main.cpp

**Comment by trishume** [comment]
I read somewhere that the red channel has better contrast for the kind of eye features I'm looking for. I forget if I did any significant testing when I changed it, but it shouldn't make that much of a difference, and probably not a negative one. ¯\\\_(ツ)\_/¯
