### ISSUE TITLE
Integration with head pose estimation

### ISSUE THREAD

**Issue by severin-lemaignan** [trishume/eyeLike#8]
--- This is not an issue per se, more a notice of re-use of your code ---

Hello!
Thanks for your implementation, it seems to perform quite well in my preliminary tests.

I'm in the process of integrating your code into my head pose estimation application, to perform head + eye gaze tracking. Pupil detection is nicely working. The integration with the overall head orientation will be done in the coming days.

Because I'm using the dlib face tracker, I get a pretty accurate contour of the eyes, that I'm using to get rid of many false detection (like with eye brows).

The branch is here:
https://github.com/severin-lemaignan/attention-tracker/tree/pupils

Thank for your contribution!

**Comment by trishume** [comment]
Nice, thanks for letting me know!

I've even used DLib's tracker [before](https://github.com/trishume/faceHack) and I thought about integrating it with eyeLike, but never did it.

Are you planning on trying to use the face tracking data as a reference to compute gaze location on a screen? If so I'm definitely interested. I'm currently doing research in HCI using eye tracking with a head-mounted Pupil Labs eye tracker, but I plan on replacing it with a webcam based solution within the next couple months.

I'm also doing head tracking with a https://www.naturalpoint.com/trackir/trackir5/ so even just the solvePNP on the Dlib data would be useful to me provided it is precise enough.

**Comment by severin-lemaignan** [comment]
@trishume yes, my aim is to integrate both the head orientation with the pupils direction to get a better estimate of the attention focus. My use case is not HCI, but HRI, but it shouldn't make much of a difference.

The accuracy of the head pose estimation is already "good enough" for many of our use case. Check the paper if you want to know a bit more about our metrics: http://academia.skadge.org/publis/lemaignan2016realtime.pdf

**Comment by trishume** [comment]
I'll definitely read that paper.

I'll probably end up looking into fancier 6dof head pose tracking since I'm using it for fine control where I need to sense 1 degree changes in angle. Unfortunately that will probably be pretty hard to implement and there is nothing open source AFAIK. I've seen papers using monocular cameras that look like they might be that precise though, so there is hope.

**Comment by severin-lemaignan** [comment]
On 09/01/2016 02:29, Tristan Hume wrote:
> I'll definitely read that paper.
>
> I'll probably end up looking into fancier 6dof head pose tracking since
> I'm using it for fine control where I need to sense 1 degree changes in
> angle. Unfortunately that will probably be pretty hard to implement and
> there is nothing open source AFAIK. I've seen papers using monocular
> cameras that look like they might be that precise though, so there is hope.

I'd be interested in knowing your results! Intuitively, I would think
that 1 degree change in head pose should be quite ok to measure, though.
If you also need accurate and absolute 6 DoF pose estimation, you of
course want a well calibrated camera and a face model that matches the
subject's anthropometrics
(https://github.com/severin-lemaignan/attention-tracker/blob/master/src/head_pose_estimation.hpp#L13)

________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, Plymouth University accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. Plymouth University does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.

**Comment by trishume** [comment]
Yah I figure that 1 degree should be doable with a normal webcam. Especially because in my use case I only need relative motion and not absolute, and I'm willing to put up with a one time per user calibration/model-building process if necessary. I'm figuring I'll have to use an actual 3d matching approach rather than a contour match with solvePNP since the contour of the face doesn't match up with the same physical points when the head is turned.
